---
- hosts: nexus
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - nexus-server/vars/main.yml
  handlers:
    - include: nexus-server/handlers/main.yml
  roles:
    - role: nexus-server

- hosts: sonarquebe
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - sonarquebe/vars/main.yml
  handlers:
    - include: sonarquebe/handlers/main.yml
  roles:
    - role: sonarquebe
  
- hosts: tomcat
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - tomcat/vars/main.yml
  handlers:
    - include: tomcat/handlers/main.yml
  roles:
    - role: tomcat

