---
- hosts: nexus
  become: yes
  roles:
    - role: ubuntu.nexus-server

    
- hosts: sonarquebe
  become: yes
  roles:
    - role: ubuntu.sonarquebe

- hosts: tomcat
  become: yes
  roles:
    - role: ubuntu.tomcat

- hosts: tomcat
  become: yes
  roles:
    - role: ubuntu.java-application
