---
- hosts: tomcat
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:

  - name: Create  sample directory
    file:
      path: "{{ tomcat_dir_path }}"
      state: directory
      mode: 0777
    become: true
    
# Deploy artifacts from nexus server to the client machine

  - name:                 Download artifact from nexus server
    maven_artifact:
      repository_url:     "{{ nexus_repo_url }}"
      group_id:           "{{ nexus_group_id }}"
      artifact_id:        "{{ artifacts_id }}"
      version:            "{{ artifacts_version }}"
      extension:          "{{ artifacts_extension }}"
      dest:               "{{ tomcat_dir_path }}"

  - name: Change ownership
    file:
      path: "{{ artifacts_path }}"
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      mode: "u+rwx,g+rx,o=rx"


