---
- hosts: tomcat
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml

  tasks:

  - name: Create  sample directory
    file:
      path: "{{ tomcat_dir_path }}"
      state: directory
      mode: 0777
    become: true
    
# Deploy artifacts from nexus server to the client machine

  - name:                 Download artifact from nexus server
    maven_artifact:
      repository_url:     "http://192.168.62.131:8081/repository/java-apps-artifacts/"
      group_id:           "com.devops4solutions"
      artifact_id:        "LoginWebApp"
      version:            "3"
      extension:          "war"
      dest:               "{{ tomcat_dir_path }}"

  - name: Change ownership
    file:
      path: "{{ artifacts_path }}"
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      mode: "u+rwx,g+rx,o=rx"
    notify: 
      - Restart Tomcat service


