---
- hosts: tomcat
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu

  vars_files:
    - vars/main.yml

  handlers:
    - include: handlers/main.yml


  tasks:
# install the packages on remote server as per requirements
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present    

  - name: install ansible
    apt:
      name: ansible
      state: present

  - name: install python3
    apt:
      name: python3
      state: present
      
  - name: install php
    apt:
      name: php
      state: present

  - name: install pip3
    apt:
      name: python3-pip
      state: present

  - name: install lxml
    pip3:
      name: lxml 

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

# Download the tomcat packages on remote server 
  - name: download & unarchive
    unarchive:
      src: http://apache.cs.utah.edu/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

 
    
 
